const PDFDocument = require('pdfkit');
const { getFromS3 } = require('./s3');

const generatePDF = async (evidenceData) => {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      // PDF ko memory mein collect karo
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // ── HEADER ──
      doc
        .fontSize(20)
        .font('Helvetica-Bold')
        .text('CYBERBULLYING INCIDENT REPORT', { align: 'center' });

      doc.moveDown(0.5);
      doc
        .fontSize(10)
        .font('Helvetica')
        .text('Generated by TraceVault — Tamper-Proof Evidence System', { align: 'center' });

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(1);

      // ── INCIDENT DETAILS ──
      doc.fontSize(13).font('Helvetica-Bold').text('INCIDENT DETAILS');
      doc.moveDown(0.5);

      doc.fontSize(11).font('Helvetica');
      doc.text(`Incident ID   :  ${evidenceData.evidence_id}`);
      doc.text(`Captured At   :  ${new Date(evidenceData.captured_at).toLocaleString('en-IN')}`);
      doc.text(`Platform URL  :  ${evidenceData.platform_url}`);
      doc.text(`Sender ID     :  ${evidenceData.sender_id}`);
      doc.text(`Device        :  ${evidenceData.device}`);
      doc.text(`Reported By   :  ${evidenceData.user_id}`);

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(1);

      // ── EVIDENCE INTEGRITY ──
      doc.fontSize(13).font('Helvetica-Bold').text('EVIDENCE INTEGRITY');
      doc.moveDown(0.5);

      doc.fontSize(11).font('Helvetica');
      doc.text(`SHA-256 Hash  :  ${evidenceData.sha256_hash}`);
      doc.text(`Hash Status   :  ${evidenceData.hash_valid ? '✅ Verified — Content Untampered' : '❌ Hash Mismatch — Possible Tampering'}`);

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(1);

      // ── SCREENSHOT ──
      doc.fontSize(13).font('Helvetica-Bold').text('CAPTURED SCREENSHOT');
      doc.moveDown(0.5);

      // S3 se image fetch karo aur embed karo
      try {
        const imageBuffer = await getFromS3(evidenceData.user_id, evidenceData.evidence_id);
        doc.image(imageBuffer, { fit: [480, 300], align: 'center' });
      } catch (imgError) {
        doc.fontSize(10).font('Helvetica').text('Screenshot could not be embedded.');
      }

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown(1);

      // ── DECLARATION ──
      doc.fontSize(13).font('Helvetica-Bold').text('DECLARATION');
      doc.moveDown(0.5);
      doc
        .fontSize(10)
        .font('Helvetica')
        .text(
          'This report was auto-generated by TraceVault. The SHA-256 hash above cryptographically verifies that the captured content has not been altered since the time of capture. This document may be submitted as supporting evidence to law enforcement or institutional complaint bodies.',
          { align: 'justify' }
        );

      doc.end();

    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generatePDF };